//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aug16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public string Descripion { get; set; }
        public string ProjectType { get; set; }
        public string Email { get; set; }
        public string HourlyRate { get; set; }
        public string iAccept { get; set; }
        public string enable { get; set; }
        public int Id { get; internal set; }
    }

}
