//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aug16.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string Descripion { get; set; }
        public string ProjectType { get; set; }
        public string Email { get; set; }
        public Nullable<int> HourlyRate { get; set; }
        public Nullable<bool> iAccept { get; set; }
        public bool enable { get; set; }
    }
}
